# Generated by Django 5.0.6 on 2024-07-15 07:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=255)),
                ('company_phonenumber', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NewWarehouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=100)),
                ('warehouse_postalcode', models.IntegerField()),
                ('warehouse_phonenumber', models.IntegerField()),
                ('warehouse_status', models.CharField(choices=[('Pending', 'Pending'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Pending', max_length=100)),
                ('warehouse_picture', models.ImageField(default='images/null.jpg', upload_to='warehouse_pictures/')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='logisticstart.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='NewItemListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_picture', models.ImageField(default='images/null.jpg', upload_to='images/')),
                ('item_name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('sender_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')])),
                ('sender_phone', models.CharField(max_length=15)),
                ('recipient_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')])),
                ('recipient_phone', models.CharField(max_length=15)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered')], default='Pending', max_length=35)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_listings', to='logisticstart.accounts')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logisticstart.newwarehouselisting')),
            ],
        ),
        migrations.CreateModel(
            name='NewWorkerListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_picture', models.ImageField(default='images/null.jpg', upload_to='worker_pictures/')),
                ('worker_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')])),
                ('worker_age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(90)])),
                ('worker_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('worker_driving_license', models.CharField(choices=[('Class 2', '2'), ('Class 2A', '2A'), ('Class 2B', '2B'), ('Class 3', '3'), ('Class 3A', '3A'), ('Class 3C', '3C'), ('Class 3CA', '3CA'), ('Class 4', '4'), ('Class 4A', '4A'), ('Class 5', '5')], max_length=30)),
                ('worker_phonenumber', models.IntegerField()),
                ('worker_NOK', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')])),
                ('worker_NOK_phonenumber', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='logisticstart.accounts')),
            ],
        ),
        migrations.CreateModel(
            name='NewDeliverySchedule',
            fields=[
                ('deliveryid', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')])),
                ('receiver_address', models.CharField(max_length=255)),
                ('receiver_number', models.CharField(max_length=15)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered')], default='Pending', max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='logisticstart.newitemlisting')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='logisticstart.newwarehouselisting')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='logisticstart.newworkerlisting')),
            ],
        ),
        migrations.CreateModel(
            name='UserBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCredits', models.IntegerField()),
                ('userPrepayments', models.IntegerField()),
                ('userTotalUsage', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='logisticstart.accounts')),
            ],
        ),
    ]
