# Generated by Django 5.0.6 on 2024-05-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=15)),
                ('sender_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=15)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
