# Generated by Django 5.0.6 on 2024-07-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newitemlisting',
            name='user',
        ),
    ]
