# Generated by Django 5.0.6 on 2024-06-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewItemListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('delivery_date', models.DateField()),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=15)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NewWarehouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(max_length=100)),
                ('warehouse_postalcode', models.IntegerField(max_length=15)),
                ('warehouse_phonenumber', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NewWorkerListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=100)),
                ('worker_age', models.IntegerField(max_length=100)),
                ('worker_gender', models.IntegerField(max_length=15)),
                ('worker_driving_license', models.CharField(max_length=100)),
                ('worker_phonenumber', models.IntegerField(max_length=15)),
                ('worker_NOK', models.CharField(max_length=100)),
                ('worker_NOK_phonenumber', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='NewListing',
        ),
    ]
