# Generated by Django 5.0.6 on 2024-07-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='account',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='logisticstart.accounts'),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='account',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='logisticstart.accounts'),
        ),
        migrations.AlterField(
            model_name='userbilling',
            name='account',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='logisticstart.accounts'),
        ),
    ]
