# Generated by Django 5.0.6 on 2024-06-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0002_newitemlisting_newwarehouselisting_newworkerlisting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newitemlisting',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=35),
        ),
        migrations.AddField(
            model_name='newwarehouselisting',
            name='warehouse_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_postalcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_NOK_phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_gender',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_phonenumber',
            field=models.IntegerField(),
        ),
    ]
