# Generated by Django 5.0.6 on 2024-06-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0003_newitemlisting_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_phonenumber',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_postalcode',
            field=models.CharField(max_length=20),
        ),
    ]
