# Generated by Django 5.0.6 on 2024-07-15 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0003_alter_newitemlisting_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='logisticstart.accounts'),
        ),
    ]
