# Generated by Django 5.0.6 on 2024-06-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0004_alter_newwarehouselisting_warehouse_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newitemlisting',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logisticstart.newwarehouselisting'),
            preserve_default=False,
        ),
    ]
