# Generated by Django 5.0.6 on 2024-07-15 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0004_alter_newwarehouselisting_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdeliveryschedule',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='logisticstart.accounts'),
        ),
    ]
