# Generated by Django 5.0.6 on 2024-06-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0005_newitemlisting_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDeliverySchedule',
            fields=[
                ('deliveryid', models.AutoField(primary_key=True, serialize=False)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_address', models.CharField(max_length=255)),
                ('receiver_number', models.IntegerField()),
                ('workerid', models.IntegerField()),
                ('warehouseid', models.IntegerField()),
                ('itemid', models.IntegerField()),
                ('delivery_status', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
