# Generated by Django 5.0.6 on 2024-06-06 08:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0006_newdeliveryschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(90)]),
        ),
    ]
