# Generated by Django 5.0.6 on 2024-06-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0007_alter_newworkerlisting_worker_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdeliveryschedule',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered')], default='Pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivering', 'Delivering'), ('Delivered', 'Delivered')], default='Pending', max_length=35),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Available', 'Available'), ('Unavailable', 'Unavailable')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_driving_license',
            field=models.CharField(choices=[('Class 2', '2'), ('Class 2A', '2A'), ('Class 2B', '2B'), ('Class 3', '3'), ('Class 3A', '3A'), ('Class 3C', '3C'), ('Class 3CA', '3CA'), ('Class 4', '4'), ('Class 4A', '4A'), ('Class 5', '5')], max_length=30),
        ),
    ]
