# Generated by Django 5.0.6 on 2024-07-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0007_alter_newdeliveryschedule_receiver_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='company_phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newdeliveryschedule',
            name='receiver_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='recipient_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='sender_phone',
            field=models.IntegerField(),
        ),
    ]
