# Generated by Django 5.0.6 on 2024-06-06 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0008_alter_newdeliveryschedule_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdeliveryschedule',
            name='receiver_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='recipient_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='recipient_phone',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='sender_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='weight',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_phonenumber',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_postalcode',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_NOK',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_NOK_phonenumber',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z]+$')]),
        ),
    ]
