# Generated by Django 5.0.6 on 2024-06-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0009_alter_newdeliveryschedule_receiver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitemlisting',
            name='weight',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_phonenumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_postalcode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_NOK_phonenumber',
            field=models.IntegerField(),
        ),
    ]
