# Generated by Django 5.0.6 on 2024-06-06 08:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0010_alter_newitemlisting_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdeliveryschedule',
            name='receiver_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='recipient_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='recipient_phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='newitemlisting',
            name='sender_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_NOK',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name must contain only letters.', regex='^[a-zA-Z ]+$')]),
        ),
    ]
