# Generated by Django 5.0.6 on 2024-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0011_alter_newdeliveryschedule_receiver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_name',
            field=models.CharField(max_length=100),
        ),
    ]
