# Generated by Django 5.0.6 on 2024-06-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0014_newitemlisting_item_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='newworkerlisting',
            name='worker_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
