# Generated by Django 5.0.6 on 2024-06-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0015_newworkerlisting_worker_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_picture',
            field=models.ImageField(blank=True, default='images/null.jpg', null=True, upload_to='images/'),
        ),
    ]
