# Generated by Django 5.0.6 on 2024-06-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0016_alter_newwarehouselisting_warehouse_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitemlisting',
            name='item_picture',
            field=models.ImageField(blank=True, default='images/null.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_picture',
            field=models.ImageField(blank=True, default='images/null.jpg', null=True, upload_to='images/'),
        ),
    ]
