# Generated by Django 5.0.6 on 2024-06-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0017_alter_newitemlisting_item_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitemlisting',
            name='item_picture',
            field=models.ImageField(default='images/null.jpg', upload_to='images/'),
        ),
    ]
