# Generated by Django 5.0.6 on 2024-06-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0018_alter_newitemlisting_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwarehouselisting',
            name='warehouse_picture',
            field=models.ImageField(default='images/null.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_picture',
            field=models.ImageField(default='images/null.jpg', upload_to='images/'),
        ),
    ]
