# Generated by Django 5.0.6 on 2024-06-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0019_alter_newwarehouselisting_warehouse_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newworkerlisting',
            name='worker_picture',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
