# Generated by Django 5.0.6 on 2024-06-19 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0021_alter_newworkerlisting_worker_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('accountID', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('company_address', models.CharField(max_length=255)),
                ('company_phonenumber', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits.', regex='^\\d{8}$')])),
            ],
        ),
    ]
