# Generated by Django 5.0.6 on 2024-06-19 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logisticstart', '0022_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='company_phonenumber',
            field=models.IntegerField(max_length=8, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits.', regex='^\\d{8}$')]),
        ),
    ]
